name: Export PostgreSQL to Excel Monthly

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas psycopg2-binary sqlalchemy openpyxl
    
    - name: Debug environment
      run: |
        echo "Checking environment variables (valores ocultos):"
        echo "DB_HOST está definido: ${{ secrets.DB_HOST != '' }}"
        echo "DB_PORT está definido: ${{ secrets.DB_PORT != '' }}"
        echo "DB_NAME está definido: ${{ secrets.DB_NAME != '' }}"
        echo "DB_USER está definido: ${{ secrets.DB_USER != '' }}"
        echo "DB_PASS está definido: ${{ secrets.DB_PASS != '' }}"
    
    - name: Run export script
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      run: |
        echo "Iniciando script..."
        python export_script.py
